//! This module handles the loading and parsing of simulation configurations.
//!
//! It reads physical system parameters, optimization constraints, and initial
//! state data from external TOML and JSON files, converting them into strongly
//! typed Rust structs for use in the main simulation loop.

use cmpe524_network_designer::models::geo::Bounds3D;
use serde::Deserialize;
use std::fs;
use std::path::Path;

// ==========================================
// 1. System Parameters (Parsed from TOML)
// ==========================================

/// Defines the physical and hardware specifications of the environment.
#[derive(Debug, Deserialize)]
pub struct SystemParams {
    /// Total number of UAVs in the simulation.
    pub uav_amount: usize,
    /// Maximum bandwidth between a User and a UAV (in Mbps).
    pub bandwidth_user_uav_mbps: f64,
    /// Maximum bandwidth between two UAVs (in Mbps).
    pub bandwidth_uav_uav_mbps: f64,
    /// CPU processing power of a single UAV (in GHz).
    pub uav_computation_capacity_ghz: f64,
    /// Maximum flying speed of the UAVs (in meters per second).
    pub uav_speed_m_s: f64,
    /// The maximum number of users a single UAV can handle simultaneously.
    pub uav_connection_limit: usize,
    /// The physical dimensions of the simulation space.
    pub area: AreaConfig,
    /// Properties about the users in the system.
    pub user: UsersConfig,
    /// Energy consumption metrics for UAV operations.
    pub energy_usage: EnergyUsageConfig,
    /// Default properties for tasks generated by users.
    pub task_profile: TaskProfileConfig,
}

/// Defines the physical 2D/3D boundaries of the simulation.
#[derive(Debug, Deserialize)]
pub struct AreaConfig {
    pub width: f64,
    pub height: f64,
}

impl AreaConfig {
    pub fn to_bounds3d(&self) -> Bounds3D {
        Bounds3D::from_width_height(self.width, self.height)
    }
}

#[derive(Debug, Deserialize)]
pub struct UsersConfig {
    pub auto_generate: bool,
    pub amount: usize,
}

/// Defines the energy costs (in Watts or Joules) for different UAV actions.
#[derive(Debug, Deserialize)]
pub struct EnergyUsageConfig {
    pub transmission: f64,
    pub computation: f64,
    // 'move' is a reserved keyword in Rust, so we rename it during parsing
    #[serde(rename = "move")]
    pub movement: f64,
    pub stall: f64,
}

/// Defines the computational load and frequency of user-generated requests.
#[derive(Debug, Deserialize)]
pub struct TaskProfileConfig {
    pub required_cycles: u64,
    pub data_size_mb: f64,
    pub requests_per_second: f64,
}

// ==========================================
// 2. Constraints (Parsed from TOML)
// ==========================================

/// Defines the Service Level Agreement (SLA) metrics used to score topologies.
#[derive(Debug, Deserialize)]
pub struct Constraints {
    /// Maximum allowed time to process a request before it is considered failed (in seconds).
    pub max_delay_tolerance_seconds: f64,
    /// The lowest acceptable ratio of successful tasks (e.g., 0.95 = 95%).
    pub min_overall_success_rate: f64,
}

// ==========================================
// 3. Initial Users (Parsed from JSON)
// ==========================================

/// Represents a user's starting location in the simulation.
#[derive(Debug, Deserialize)]
pub struct InitialUser {
    pub id: u32,
    pub x: f64,
    pub y: f64,
}

// ==========================================
// Loader Functions
// ==========================================

/// Loads and parses the system parameters TOML file
pub fn load_system_params<P: AsRef<Path>>(path: P) -> SystemParams {
    let content =
        fs::read_to_string(path).expect("Failed to read system_params.toml. Does the file exist?");
    toml::from_str(&content)
        .expect("Failed to parse system_params.toml. Check for formatting errors.")
}

/// Loads and parses the constraints TOML file
pub fn load_constraints<P: AsRef<Path>>(path: P) -> Constraints {
    let content = fs::read_to_string(path).expect("Failed to read constraints.toml.");
    toml::from_str(&content).expect("Failed to parse constraints.toml.")
}

/// Loads and parses the initial users JSON file
pub fn load_initial_users<P: AsRef<Path>>(path: P) -> Vec<InitialUser> {
    let content = fs::read_to_string(path).expect("Failed to read initial_users.json.");
    serde_json::from_str(&content).expect("Failed to parse initial_users.json.")
}

// ==========================================
// Tests
// ==========================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_system_params() {
        // Using a raw string literal to simulate the TOML file content
        let toml_content = r#"
            uav_amount = 5
            bandwidth_user_uav_mbps = 20.0
            bandwidth_uav_uav_mbps = 100.0
            uav_computation_capacity_ghz = 3.0
            uav_speed_m_s = 15.0
            uav_connection_limit = 50

            [area]
            width = 1000.0
            height = 1000.0

            [energy_usage]
            transmission = 0.5
            computation = 1.2
            move = 25.0
            stall = 5.0

            [task_profile]
            required_cycles = 1000000000
            data_size_mb = 2.5
            requests_per_second = 0.5
        "#;

        // Test that it parses without panicking
        let params: SystemParams = toml::from_str(toml_content).unwrap();

        // Verify specific fields
        assert_eq!(params.uav_amount, 5);
        assert_eq!(params.area.width, 1000.0);

        // Critically: Verify the Serde rename worked!
        // The TOML says "move", but our struct says "movement"
        assert_eq!(params.energy_usage.movement, 25.0);
    }

    #[test]
    fn test_parse_constraints() {
        let toml_content = r#"
            max_delay_tolerance_seconds = 1.5
            min_overall_success_rate = 0.95 
        "#;

        let constraints: Constraints = toml::from_str(toml_content).unwrap();
        assert_eq!(constraints.max_delay_tolerance_seconds, 1.5);
        assert_eq!(constraints.min_overall_success_rate, 0.95);
    }

    #[test]
    fn test_parse_initial_users() {
        let json_content = r#"
        [
            { "id": 1, "x": 150.5, "y": 200.0 },
            { "id": 2, "x": 450.0, "y": 800.2 }
        ]
        "#;

        let users: Vec<InitialUser> = serde_json::from_str(json_content).unwrap();
        assert_eq!(users.len(), 2);
        assert_eq!(users[0].id, 1);
        assert_eq!(users[1].y, 800.2);
    }
}
